# Generated by Django 4.2.6 on 2023-11-28 21:49

from django.db import migrations, models


def add_category_foreign_key(apps, schema_editor):
    Post = apps.get_model('news', 'Post')
    Category = apps.get_model('news', 'Category')
    schema_editor.add_constraint(
        Post,
        models.ForeignKey(
            Category,
            on_delete=models.CASCADE,
            related_name='posts',
            null=True,  # Укажите null=True, если вы хотите разрешить пустое значение для внешнего ключа
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_category_foreign_key),
    ]
