# Generated by Django 4.2.6 on 2023-11-19 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
